name: Test shell commands

on: [push]

jobs:
  get-changed-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          token: ${{ secrets.TOK }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *"config.yml" ]] || [[ "$file" == *".env" ]]; then
              echo "This is file: $file"
              DIR="${file: :-10}"
              export $(grep 'PROMETHEUS_HOSTNAME=' ${DIR}.env | xargs)
              echo "inside dir: $DIR"
              echo $PROMETHEUS_HOSTNAME
              docker build . --build-arg dir=$DIR -t ashiful/kaktarua:${PROMETHEUS_HOSTNAME}
              docker push ashiful/kaktarua:${PROMETHEUS_HOSTNAME}
            fi
          done
          docker images
