name: Test shell commands

on: [push]

jobs:
  run-on-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.TOK }}
      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *"$config.yml" ]]; then
              echo "$file ."
              DIR="${file: :-10}"
              export $(grep -v '^#' ${DIR}.env | xargs)
              echo $DIR
              echo $PROMETHEUS_HOSTNAME
            fi
          done
