name: Test shell commands

on: [push]

jobs:
  run-on-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get user
        run: |
          echo "test"
      - name: Run script on docker
        uses: docker://node:10.13-alpine
        with:
          entrypoint: ./myscript.sh
