name: Test shell commands

on: [push]

jobs:
  run-on-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: |
          'curl -x POST http://localhost:3001/api/user -H ''content-type: application/json'' -d ''{"username": "hello","address": "road"}'''
      - name: Get user
        run: curl http:localhost:3001/api/users
